# Generated by Django 4.0.6 on 2022-07-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0015_alter_mailsender_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailsender',
            old_name='unique_id',
            new_name='uniq_id',
        ),
    ]
