# Generated by Django 4.0.6 on 2022-07-26 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0016_rename_unique_id_mailsender_uniq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsender',
            name='uniq_id',
            field=models.CharField(default=uuid.uuid4, max_length=500, null=True),
        ),
    ]
