# Generated by Django 4.0.6 on 2022-08-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password_confirmation',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
