# Generated by Django 4.0.6 on 2022-08-07 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_useraccount_password_confirmation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='password_confirmation',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='number_of_contacts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
