# Generated by Django 4.0.6 on 2022-08-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccount_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='password_confirmation',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
