# Generated by Django 4.0.6 on 2022-07-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0002_alter_mailsender_to_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsender',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/newfile'),
        ),
    ]
