# Generated by Django 4.0.6 on 2022-07-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0003_mailsender_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailsender',
            name='file',
        ),
        migrations.AddField(
            model_name='mailsender',
            name='email_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
