# Generated by Django 4.0.6 on 2022-07-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0004_remove_mailsender_file_mailsender_email_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsender',
            name='uniq_id',
            field=models.CharField(default='32', max_length=8),
        ),
    ]
