# Generated by Django 4.0.6 on 2022-07-26 01:49

from django.db import migrations, models
import mail_sender.models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0006_alter_mailsender_uniq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsender',
            name='uniq_id',
            field=models.CharField(default=mail_sender.models.create_id, max_length=8),
        ),
    ]
