# Generated by Django 4.0.6 on 2022-07-26 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0008_alter_mailsender_uniq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsender',
            name='uniq_id',
            field=models.CharField(default=uuid.uuid4, max_length=8),
        ),
    ]
