# Generated by Django 4.0.6 on 2022-07-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailsender',
            name='unique_id',
        ),
    ]
